# Продакшен

# команда запуска
# docker-compose -f docker-compose-production.yml build
# docker-compose -f docker-compose-production.yml up
# docker-compose -f docker-compose-production.yml ps
# docker-compose -f docker-compose-production.yml down

# IDEA: 31-01-2020
# Создать дамп данных
# команда запуска 
# docker exec lpc-mongodb sh -c 'exec mongodump -d lpcdb --out /lpc_dump/'
#
# Восстановить данные из бекапа
# команда запуска 
# docker exec lpc-mongodb sh -c 'mongorestore -v -d lpcdb /lpc_dump/lpcdb/'

version: '3'

services:
  nodejs:
    container_name: lpc-node-server
    build: server/
    command: node ./src/start.js
    restart: always
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
    volumes:
      - '/home/little/lpc_images:/home/lpc_images'

  mongo:
    image: mongo:4.2.0
    container_name: lpc-mongodb
    restart: always
    volumes:
      - '/home/little/lpc_db/:/data/db'
      - '/home/little/lpc_mongodb_logs:/var/log/mongodb'
      - '/home/little/lpc_db_dump:/lpc_dump'
    command: 
      - mongod
      - '--logpath'
      - '/var/log/mongodb/mongodb.log'

  nginx:
    container_name: lpc-nginx
    build: nginx/
    restart: always
    ports:
      - '80:8077'
      - '443:443'
    depends_on:
      - mongo
      - nodejs
    volumes:
      - './client/build:/usr/share/nginx/html:ro'
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - '/home/little/lpc_nginx_logs:/var/logs'
      - '/home/little/lpc_https:/etc/nginx/ssl'
      - '/home/little/lpc_images:/home/lpc_images'
      - '/home/little/lpc_acme:/home/lpc_acme'
