export {
  isFetching,
  headers,
  totalPages,
  currentPage,
  data,
  citiesList,
  isFetchingSecond,
  isFetchingArticle,
  dataArticle,
  isAlreadyChashed,
  result,
  resultArticle,
  isFetchingCategories,
  resultCategories,
} from './selectors';
