export {
  // Actions
  citiesRequest,
  citiesSuccess,
  citiesFailure,
  citiesResult,
  citiesSecondRequest,
  citiesSecondResult,
  citiesCityRequest,
  citiesCitySuccess,
  citiesCityFailure,
  citiesCityResult,
  citiesCategoriesRequest,
  citiesCategoriesSuccess,
  citiesCategoriesFailure,
  citiesCategoriesResult,
  citiesFilteredRequest,
  citiesFilteredSuccess,
  citiesFilteredFailure,
  citiesFilteredResult,
  citiesSecondFilteredRequest,
  citiesSecondFilteredResult,
  // Root Reducer
  default as citiesReducer,
} from './duck';
